### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by Caealana** [standerson/intro-data-capstone-biodiversity#5]
Congratulations on successfully completing your capstone project for the data analysis course!

I was impressed with how you expertly interspersed your charts, tables, and codes to provide adequate evidence for your conclusions and ideas. Your code was also extremely neat and easy to read from the slides. You did a great job at making sure your slides did not get too cluttered. 

I would just suggest you work on implementing transitions and context information so that your presentation reads more like a cohesive story instead of a collection of facts.

**Comment by standerson** [comment]
Thanks for all the excellent comments.
